DROP TABLESPACE DATA_ROT;

CREATE TABLESPACE DATA_ROT
  DATAFILE 'tbs_data_rot.dat' 
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

DROP USER CGSYSADM CASCADE;

CREATE USER CGSYSADM IDENTIFIED BY "cgsysadm17";

GRANT CONNECT, RESOURCE TO CGSYSADM;

GRANT CREATE ANY TABLE, DROP ANY TABLE, CREATE PUBLIC SYNONYM, CREATE VIEW, CREATE TRIGGER TO CGSYSADM;

ALTER USER "CGSYSADM"
DEFAULT TABLESPACE "DATA_ROT"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

ALTER USER "CGSYSADM" QUOTA UNLIMITED ON "DATA_ROT";

QUIT
/
