--------------------------------------------------------
--  DDL for Table
--------------------------------------------------------

DROP TABLE "CGSYSADM"."GLACCOUNTS";

CREATE TABLE "CGSYSADM"."GLACCOUNTS" (
	   GLACODE VARCHAR2(30),
	   GLADESC VARCHAR2(60),
	   GLATYPE VARCHAR(2),
	   GLACTIVE VARCHAR(1),
	   ENTRY_DATE DATE,
	   ENTRY_OWNER VARCHAR2(16),
	   UPDATE_DATE DATE,
	   UPDATE_OWNER VARCHAR2(16)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

--------------------------------------------------------
--  DDL for Index
--------------------------------------------------------

CREATE UNIQUE INDEX "CGSYSADM"."PK_GL_ACCT_IDX" ON "CGSYSADM"."GLACCOUNTS" ("GLACODE") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

--------------------------------------------------------
--  DDL for Constraints
--------------------------------------------------------

ALTER TABLE "CGSYSADM"."GLACCOUNTS"
ADD CONSTRAINT "PK_GL_ACCT_IDX" PRIMARY KEY ("GLACODE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ENABLE;

ALTER TABLE "CGSYSADM"."GLACCOUNTS" MODIFY ("GLACODE" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."GLACCOUNTS" MODIFY ("GLADESC" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."GLACCOUNTS" MODIFY ("GLATYPE" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."GLACCOUNTS" MODIFY ("GLACTIVE" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."GLACCOUNTS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."GLACCOUNTS" MODIFY ("ENTRY_OWNER" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Grants
--------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON "CGSYSADM"."GLACCOUNTS" TO SAMAPI;

--------------------------------------------------------
--  DDL for Synoyms
--------------------------------------------------------

CREATE OR REPLACE PUBLIC SYNONYM GLACCOUNTS FOR "CGSYSADM"."GLACCOUNTS";

QUIT
/

