--------------------------------------------------------
--  DDL for Table
--------------------------------------------------------

CREATE TABLE "CGSYSADM"."CUSTOMER_SEGMENT" (
	CSTRADEREF VARCHAR2(8),
	SEGM_CATEGORY VARCHAR2(8),
	ENTRY_DATE DATE,
	ENTRY_OWNER VARCHAR2(16),
	UPDATE_DATE DATE,
	UPDATE_OWNER VARCHAR2(16),
	REC_VERSION INTEGER DEFAULT 0
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

COMMENT ON COLUMN "CGSYSADM"."CUSTOMER_SEGMENT"."CSTRADEREF" IS 'Customer segment group codes for SAP account orders';
COMMENT ON TABLE "CGSYSADM"."CUSTOMER_SEGMENT"  IS 'Customer segment codees deictionary for SAP account orders';

--------------------------------------------------------
--  DDL for Index
--------------------------------------------------------

CREATE UNIQUE INDEX "CGSYSADM"."PK_CUST_SEGM_IDX" ON "CGSYSADM"."CUSTOMER_SEGMENT" ("CSTRADEREF") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

--------------------------------------------------------
--  DDL for Constraints
--------------------------------------------------------

ALTER TABLE "CGSYSADM"."CUSTOMER_SEGMENT"
ADD CONSTRAINT "PK_CUST_SEGM_IDX" PRIMARY KEY ("CSTRADEREF")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT"  ENABLE;

ALTER TABLE "CGSYSADM"."CUSTOMER_SEGMENT" MODIFY ("CSTRADEREF" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."CUSTOMER_SEGMENT" MODIFY ("SEGM_CATEGORY" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Grants
--------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON "CGSYSADM"."CUSTOMER_SEGMENT" TO SAMAPI;

--------------------------------------------------------
--  DDL for Synoyms
--------------------------------------------------------

CREATE OR REPLACE PUBLIC SYNONYM CUSTOMER_SEGMENT FOR "CGSYSADM"."CUSTOMER_SEGMENT";

QUIT
/
