--------------------------------------------------------
--  DDL for Table
--------------------------------------------------------

DROP TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS_LOG";

CREATE TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS_LOG" (
	OPCODE CHAR(1),
	OPDATE DATE,													  
	STATUS CHAR(1),
	RELEASE_ID INTEGER,
	BSCS_ACCOUNT VARCHAR2(32),
	SEGMENT_CODE VARCHAR2(32),
	VALID_FROM_DATE DATE,
	ORDER_NUMBER VARCHAR2(32),
	ENTRY_DATE DATE,
	ENTRY_OWNER VARCHAR2(16),
	UPDATE_DATE DATE,
	UPDATE_OWNER VARCHAR2(16),
	RELEASE_DATE DATE,
	RELEASE_OWNER VARCHAR2(16),
	REC_VERSION INTEGER
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

--------------------------------------------------------
--  DDL for Index
--------------------------------------------------------

CREATE INDEX "CGSYSADM"."PK_SAP_ACCT_SEGM_LOG_IDX" ON "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS_LOG" ("BSCS_ACCOUNT") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

--------------------------------------------------------
--  DDL for Constraints
--------------------------------------------------------

ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS_LOG" MODIFY ("OPCODE" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS_LOG" MODIFY ("OPDATE" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Grants
--------------------------------------------------------

GRANT SELECT, INSERT ON "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS_LOG" TO SAMAPI;

--------------------------------------------------------
--  DDL for Synoyms
--------------------------------------------------------

CREATE OR REPLACE PUBLIC SYNONYM SAP_ACC_SEGM_ORDER_NUMBERS_LOG FOR "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS_LOG";

QUIT
/
