--------------------------------------------------------
--  DDL for Table
--------------------------------------------------------

CREATE TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" (
	STATUS CHAR(1),
	RELEASE_ID INTEGER,
	BSCS_ACCOUNT VARCHAR2(32),
	SEGMENT_CODE VARCHAR2(32),
	VALID_FROM_DATE DATE,
	ORDER_NUMBER VARCHAR2(32),
	ENTRY_DATE DATE,
	ENTRY_OWNER VARCHAR2(16),
	UPDATE_DATE DATE,
	UPDATE_OWNER VARCHAR2(16),
	RELEASE_DATE DATE,
	RELEASE_OWNER VARCHAR2(16),
    REC_VERSION INTEGER	 DEFAULT 0												  
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

COMMENT ON COLUMN "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"."STATUS" IS 'Status of the ntry, W like Working, C like Controlled, P like Production';
COMMENT ON COLUMN "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"."RELEASE_ID" IS 'Running identifier of the release, 0 for Work, else for Production release versions';
COMMENT ON COLUMN "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"."BSCS_ACCOUNT" IS 'BSCS GL account code used for booking, source of the mapping';
COMMENT ON COLUMN "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"."SEGMENT_CODE" IS 'Customer segment code from CUSTOMER_SEGMENT dictionary table, all values to be used';
COMMENT ON COLUMN "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"."ORDER_NUMBER" IS 'Number of the order to be filled in by Control';

--------------------------------------------------------
--  DDL for Index
--------------------------------------------------------

CREATE UNIQUE INDEX "CGSYSADM"."PK_SAP_ACCT_SEGM_IDX" ON "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" ("STATUS", "RELEASE_ID", "BSCS_ACCOUNT", "SEGMENT_CODE") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

--------------------------------------------------------
--  DDL for Constraints
--------------------------------------------------------

ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"
ADD CONSTRAINT "PK_SAP_ACCT_SEGM_IDX" PRIMARY KEY ("STATUS", "RELEASE_ID", "BSCS_ACCOUNT", "SEGMENT_CODE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ENABLE;

ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" MODIFY ("STATUS" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" MODIFY ("RELEASE_ID" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" MODIFY ("BSCS_ACCOUNT" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" MODIFY ("SEGMENT_CODE" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" MODIFY ("ENTRY_OWNER" NOT NULL ENABLE);

ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"
ADD CONSTRAINT FK_SAP_ACC_SEGM_ORD_SEGM
FOREIGN KEY (SEGMENT_CODE)
REFERENCES CUSTOMER_SEGMENT (CSTRADEREF);

ALTER TABLE "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS"
ADD CONSTRAINT FK_SAP_ACC_SEGM_ORD_BSCS_ACC
FOREIGN KEY (STATUS, RELEASE_ID, BSCS_ACCOUNT)
REFERENCES SAP_ACCOUNTS (STATUS, RELEASE_ID, BSCS_ACCOUNT);

--------------------------------------------------------
--  DDL for Grants
--------------------------------------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS" TO SAMAPI;

--------------------------------------------------------
--  DDL for Synoyms
--------------------------------------------------------

CREATE OR REPLACE PUBLIC SYNONYM SAP_ACC_SEGM_ORDER_NUMBERS FOR "CGSYSADM"."SAP_ACC_SEGM_ORDER_NUMBERS";

QUIT
/
