--------------------------------------------------------
--  DDL for Triggers
--------------------------------------------------------
CREATE OR REPLACE TRIGGER SAP_ACC_SEGM_ORD_NUM_bef_ins
BEFORE INSERT
   ON SAP_ACC_SEGM_ORDER_NUMBERS
   FOR EACH ROW
BEGIN
   IF :new.STATUS = 'P' AND :new.VALID_FROM_DATE < SYSDATE THEN
	  RAISE_APPLICATION_ERROR(-20000, 'Valid Date in the past, validation error');
   END IF;
   :new.VALID_FROM_DATE := ROUND(TO_DATE(:new.VALID_FROM_DATE),'DAY');   
END;
/

SHOW ERRORS

CREATE OR REPLACE TRIGGER SAP_ACC_SEGM_ORD_NUM_aft_ins
AFTER INSERT
   ON SAP_ACC_SEGM_ORDER_NUMBERS
   FOR EACH ROW
BEGIN
   INSERT INTO SAP_ACC_SEGM_ORDER_NUMBERS_LOG
   (
    OPCODE,
	OPDATE,
	STATUS,
	RELEASE_ID,
	BSCS_ACCOUNT,
	SEGMENT_CODE,
	VALID_FROM_DATE,
	ORDER_NUMBER,
	ENTRY_DATE,
	ENTRY_OWNER,
	UPDATE_DATE,
	UPDATE_OWNER,
	RELEASE_DATE,
	RELEASE_OWNER,
	REC_VERSION
   )
   VALUES
   (
	'I',
	SYSDATE,
	:new.STATUS,
	:new.RELEASE_ID,
	:new.BSCS_ACCOUNT,
	:new.SEGMENT_CODE,
	:new.VALID_FROM_DATE,
	:new.ORDER_NUMBER,
	:new.ENTRY_DATE,
	:new.ENTRY_OWNER,
	:new.UPDATE_DATE,
	:new.UPDATE_OWNER,
	:new.RELEASE_DATE,
	:new.RELEASE_OWNER,
	:new.REC_VERSION
   );
END;
/

SHOW ERROR

CREATE OR REPLACE TRIGGER SAP_ACC_SEGM_ORD_NUM_bef_upd
BEFORE UPDATE
   ON SAP_ACC_SEGM_ORDER_NUMBERS
   FOR EACH ROW
BEGIN
   IF :new.STATUS = 'P' AND :new.VALID_FROM_DATE < SYSDATE THEN
	  RAISE_APPLICATION_ERROR(-20000, 'Valid Date in the past, validation  error');
   END IF;
   :new.REC_VERSION := :old.REC_VERSION + 1;
   :new.VALID_FROM_DATE := ROUND(TO_DATE(:new.VALID_FROM_DATE),'DAY');   
END;
/

SHOW ERRORS

CREATE OR REPLACE TRIGGER SAP_ACC_SEGM_ORD_NUM_aft_upd
AFTER UPDATE
   ON SAP_ACC_SEGM_ORDER_NUMBERS
   FOR EACH ROW
BEGIN
   INSERT INTO SAP_ACC_SEGM_ORDER_NUMBERS_LOG
   (
    OPCODE,
	OPDATE,
	STATUS,
	RELEASE_ID,
	BSCS_ACCOUNT,
	SEGMENT_CODE,
	VALID_FROM_DATE,
	ORDER_NUMBER,
	ENTRY_DATE,
	ENTRY_OWNER,
	UPDATE_DATE,
	UPDATE_OWNER,
	RELEASE_DATE,
	RELEASE_OWNER,
	REC_VERSION
   )
   VALUES
   (
	'U',
	SYSDATE,
	:new.STATUS,
	:new.RELEASE_ID,
	:new.BSCS_ACCOUNT,
	:new.SEGMENT_CODE,
	:new.VALID_FROM_DATE,
	:new.ORDER_NUMBER,
	:new.ENTRY_DATE,
	:new.ENTRY_OWNER,
	:new.UPDATE_DATE,
	:new.UPDATE_OWNER,
	:new.RELEASE_DATE,
	:new.RELEASE_OWNER,
	:new.REC_VERSION
   );
END;
/

SHOW ERROR

CREATE OR REPLACE TRIGGER SAP_ACC_SEGM_ORD_NUM_bef_del
BEFORE DELETE
   ON SAP_ACC_SEGM_ORDER_NUMBERS
   FOR EACH ROW
BEGIN
   IF :old.STATUS = 'P' AND :old.VALID_FROM_DATE < SYSDATE THEN
	  RAISE_APPLICATION_ERROR(-20000, 'Valid Date in the past, validation error');
   END IF;	  
END;
/

SHOW ERRORS

CREATE OR REPLACE TRIGGER SAP_ACC_SEGM_ORD_NUM_aft_del
AFTER DELETE
   ON SAP_ACC_SEGM_ORDER_NUMBERS
   FOR EACH ROW
BEGIN
   INSERT INTO SAP_ACC_SEGM_ORDER_NUMBERS_LOG
   (
	OPCODE,
	OPDATE,
	STATUS,
	RELEASE_ID,
	BSCS_ACCOUNT,
	SEGMENT_CODE,
	VALID_FROM_DATE,
	ORDER_NUMBER,
	ENTRY_DATE,
	ENTRY_OWNER,
	UPDATE_DATE,
	UPDATE_OWNER,
	RELEASE_DATE,
	RELEASE_OWNER,
	REC_VERSION
   )
   VALUES
   (
	'D',
	SYSDATE,
	:old.STATUS,
	:old.RELEASE_ID,
	:old.BSCS_ACCOUNT,
	:old.SEGMENT_CODE,
	:old.VALID_FROM_DATE,
	:old.ORDER_NUMBER,
	:old.ENTRY_DATE,
	:old.ENTRY_OWNER,
	:old.UPDATE_DATE,
	:old.UPDATE_OWNER,
	:old.RELEASE_DATE,
	:old.RELEASE_OWNER,
	:old.REC_VERSION
   );
END;
/

SHOW ERROR

QUIT
/

